name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.3.4
#author: Jakub Homlala <jhomlala@gmail.com>
#author: Ilia Kurtov <ilia.kurtov@gmail.com>
homepage: https://github.com/klar-mx/alice

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  rxdart: ^0.27.7

  package_info_plus: ^4.0.2
  share_plus: ^12.0.1
  url_launcher: ^6.1.6
  collection: ^1.18.0
  meta: ^1.1.0

dev_dependencies:
  very_good_analysis: ^5.1.0
